"""
Docusaurus format exporter.

Converts generated documents into Docusaurus-compatible MDX files
with frontmatter, and generates a sidebars.js configuration.
"""

from __future__ import annotations

import json
from typing import Any

from app.docgen.models import DocType, GeneratedDocument
from app.docgen.renderer import render_markdown

# Map doc types to Docusaurus categories and positions
_DOC_TYPE_CONFIG: dict[str, dict[str, Any]] = {
    DocType.README: {"category": "", "position": 1, "id": "intro"},
    DocType.ARCHITECTURE: {"category": "", "position": 2, "id": "architecture"},
    DocType.ONBOARDING: {"category": "", "position": 3, "id": "onboarding"},
    DocType.RUNBOOK: {"category": "", "position": 4, "id": "runbook"},
    DocType.MODULE: {"category": "modules", "position": 10, "id": ""},
    DocType.API_REFERENCE: {"category": "api", "position": 20, "id": ""},
    DocType.FLOW: {"category": "flows", "position": 30, "id": ""},
    DocType.DEPENDENCY_MAP: {"category": "", "position": 5, "id": "dependencies"},
    DocType.CHANGELOG: {"category": "", "position": 6, "id": "changelog"},
}


def render_docusaurus(doc: GeneratedDocument) -> str:
    """Render a single document as Docusaurus MDX with frontmatter."""
    config = _DOC_TYPE_CONFIG.get(doc.doc_type, {"category": "", "position": 99, "id": ""})

    doc_id = config["id"] or _slugify(doc.scope_id or doc.title)
    position = config["position"]

    # For scoped docs (modules, api refs), adjust position by scope
    if doc.scope_id:
        # Use hash of scope_id for stable ordering
        position += hash(doc.scope_id) % 100

    tags = ["auto-generated", doc.doc_type]
    if doc.scope_id:
        tags.append(doc.scope_id)

    frontmatter = [
        "---",
        f"id: {doc_id}",
        f"title: {doc.title}",
        f"sidebar_position: {position}",
        f"tags: {json.dumps(tags)}",
        "---",
        "",
    ]

    # Render body (reuse markdown renderer but strip the H1 title since Docusaurus uses frontmatter)
    md = render_markdown(doc)
    # Remove first H1 line and the auto-generated note
    lines = md.split("\n")
    body_lines = []
    skip_header = True
    for line in lines:
        if skip_header:
            if (
                line.startswith("# ")
                or line.startswith("> Auto-generated")
                or line.startswith("> Scope:")
                or not line.strip()
            ):
                continue
            skip_header = False
        body_lines.append(line)

    return "\n".join(frontmatter + body_lines)


def generate_sidebars(docs: list[GeneratedDocument]) -> str:
    """Generate a sidebars.js for Docusaurus from a list of documents."""
    # Group by category
    top_level: list[dict[str, Any]] = []
    categories: dict[str, list[dict[str, Any]]] = {}

    for doc in docs:
        config = _DOC_TYPE_CONFIG.get(doc.doc_type, {"category": "", "position": 99, "id": ""})
        doc_id = config["id"] or _slugify(doc.scope_id or doc.title)
        category = config["category"]

        if category:
            categories.setdefault(category, []).append({
                "id": f"{category}/{doc_id}",
                "position": config["position"],
            })
        else:
            top_level.append({
                "id": doc_id,
                "position": config["position"],
            })

    # Sort
    top_level.sort(key=lambda x: x["position"])
    for cat_items in categories.values():
        cat_items.sort(key=lambda x: x["position"])

    # Build sidebar structure
    sidebar_items: list[Any] = [item["id"] for item in top_level]

    for cat_name, items in sorted(categories.items()):
        sidebar_items.append({
            "type": "category",
            "label": cat_name.replace("_", " ").title(),
            "items": [item["id"] for item in items],
        })

    sidebar_obj = {"docs": sidebar_items}

    return (
        "// Auto-generated by Eidos documentation engine\n"
        f"module.exports = {json.dumps(sidebar_obj, indent=2)};\n"
    )


def build_docusaurus_structure(
    docs: list[GeneratedDocument],
) -> dict[str, str]:
    """Build a complete Docusaurus file structure.

    Returns a dict mapping relative file paths to content.
    """
    files: dict[str, str] = {}

    for doc in docs:
        config = _DOC_TYPE_CONFIG.get(doc.doc_type, {"category": "", "position": 99, "id": ""})
        category = config["category"]
        doc_id = config["id"] or _slugify(doc.scope_id or doc.title)

        if category:
            path = f"docs/{category}/{doc_id}.md"
        else:
            path = f"docs/{doc_id}.md"

        files[path] = render_docusaurus(doc)

    # Sidebars
    files["sidebars.js"] = generate_sidebars(docs)

    return files


def _slugify(text: str) -> str:
    """Convert text to a URL-safe slug."""
    return (
        text.lower()
        .replace(" ", "-")
        .replace(".", "-")
        .replace("/", "-")
        .replace("_", "-")
        .strip("-")
    )
